# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Huzaima Khan | Programming tutorials"
description: > # this means to ignore newlines until "baseurl:"
  This blog is all about programming tutorials. Primarily in Microsoft AX Dynamics 2012 and Dynamics 365
baseurl: ""
url: "https://huzaima.github.io"
permalink: /:title
repository: huzaima/huzaima.github.io
paginate: 5

# MatJek specific configurations
github_profile: "https://github.com/huzaima/"
user: "Huzaima Khan"
user_email: "khanhuzaima@gmail.com"
contact_url: "https://goo.gl/tVljbV"
linkedin_url: "https://www.linkedin.com/in/huzaima-khan/"
current_designation: "Microsoft AX Dynamics Developer"
current_company_name: "Systems Limited"
current_company_url: "https://systemsltd.com/"
google_tracking_id: "UA-43371761-3"
google_site_verification: "UA-43371761-3"
disqus_shortname: "huzaimagithubio"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
